### PR TITLE
Added CondFormat to store optical functions

### PR DESCRIPTION
**Pull request by jan-kaspar**

### CODE REVIEW

**Comment by jan-kaspar** [comment]
@wpcarvalho This is a proposal for the class holding the optical functions. Please let me know if looks OK from the point of view of future DB storage. Thanks!

**Comment by jan-kaspar** [comment]
@fabferro @forthommel FYI: after long talking, now I start to seriously work on the PR preparation. I will commit to this branch.

**Comment by forthommel** [comment]
Very good! I will include the reco::ProtonTrack DF definition here too! It might be interesting to stash a bit the other branches' 160+ commits as any rebase is excruciatingly long these days :)

**Comment by jan-kaspar** [comment]
Closing this PR in favour of a more complete one.

**Pull request closed without merging**
