### PR TITLE
Cleanup of proton reco packages

### PR DESCRIPTION
**Pull request by forthommel**
A few "good CMS packages development practices" implemented in the reconstruction branch, such as:
* replacement of `_cfi` standard parameters definition with proper modules `fillDescription` static method (useful e.g. for future HLT studies with simulation/reco)
* usage of `default` constructor/destructor whenever possible
* homogenisation of coding standards wherever possible.

### CODE REVIEW

**Comment by jan-kaspar** [comment]
Thanks @forthommel , I will check it (relatively) soon!

**Comment by jan-kaspar** [comment]
Thanks again @forthommel 

There are several places where I would have preferred the original indentation/style - but this is a matter of taste. And if your changes make it more CMSSW-like, fine with me!

Then there are two things I don't like.

The change of print-outs here
https://github.com/CTPPS/cmssw/pull/36/commits/207db5a694a6d78b7980a0a1cc247882c0e0d984#diff-fd3adccde41a0a433140fe134fe1f43fL150
and following. As it was done before, the entire "reconstruction report" from one event was issued as one message, with one set of header and footer - something well readable. With your changes there would be many messages, which I find a mess. Also, I prefer LogInfo over LogDebug, since AFAIk for the latter one needs to recompile the SW to see the effect.

The use of "for_each" here:
https://github.com/CTPPS/cmssw/pull/36/commits/207db5a694a6d78b7980a0a1cc247882c0e0d984#diff-fd3adccde41a0a433140fe134fe1f43fR173
For me, it makes the code more complicate to read. Are there any other benefits of this construct?

Finally a question: is it forbidden to include ".gitignore" files? I find them useful under "test" directories, since the test configs there are likely to produce output which should not go to the release.

Unless you have counter-arguments to what I have written above, could you please undo the 2 (or 3) changes, please?

**Comment by forthommel** [comment]
Sorry, forgot the last comment about `.gitignore` files! As far as I can remember I was asked in a previous request to drop all of them. Not sure if that's a valid argument, but a [quick search](https://github.com/cms-sw/cmssw/search?q=.gitignore&unscoped_q=.gitignore) in the full CMSSW repository only gives a single hit, which probably means I was not the only one asked to do so.

**Comment by jan-kaspar** [comment]
Thanks again @forthommel !

For style/indentation, in general, as long as I can read the code without much struggle, I'm fine with any solution. Still needless to say that I have my own preferences...

Thanks for the hint on `.gitignore` files.

Thanks for pointing out the hard-coded mass here:
https://github.com/CTPPS/cmssw/pull/36/commits/d7dd69d5274f6fe8cd4aec2fc9abbbe7cfc9e919#diff-8889c94e3d4adbc3aebf8d2cafaf73baR24
For me, the best solution is a static class function - another potential benefit for class users. What do you think? Will you take care or shall I do it?

**Pull request merged**
